name: Arduino CI

on: [push]

# jobs run in parallel

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: run hello world
              run: echo "say hello to everyone"  
            #checkout repo
            - name: Checkout repository 
              uses: actions/checkout@v5
            # compile Arduino sketch 
            - name: compile Arduino Sketches
              uses: arduino/compile-sketches@v1
              with: 
                fqbn: "arduino:avr:uno"